-- =====================================================================
--  SCHEMA DATABASE
--  Sistem Akuntansi Pendapatan Sewa Lapangan Padel - Smash Padel Club
-- ---------------------------------------------------------------------
--  URUTAN MENJALANKAN (di Supabase > SQL Editor):
--    1. schema.sql   (file ini)  -> membuat tabel, relasi, view, keamanan
--    2. triggers.sql             -> membuat fungsi & trigger jurnal otomatis
--    3. seed.sql                 -> mengisi data contoh
--
--  PERHATIAN: bagian "RESET" di bawah akan MENGHAPUS semua tabel
--  beserta isinya. Aman dijalankan di project baru, tapi jangan
--  dijalankan ulang kalau datamu sudah penting.
-- =====================================================================


-- ---------------------------------------------------------------------
-- RESET: hapus objek lama (kalau pernah dibuat) supaya bisa diulang
-- ---------------------------------------------------------------------
drop view  if exists v_booking_lengkap, v_pembayaran_lengkap, v_pembelian_paket_lengkap,
                     v_sewa_lengkap, v_jurnal_lengkap cascade;
drop table if exists jurnal_detail, jurnal, sewa_peralatan, peralatan, pembayaran,
                     booking, pembelian_paket, akun, paket_member, pelanggan, lapangan cascade;


-- =====================================================================
--  A. TABEL MASTER (data pokok)
-- =====================================================================

-- 1. LAPANGAN: daftar lapangan padel beserta tarif per jam
create table lapangan (
  id            bigint generated by default as identity primary key,
  nama          text not null unique,
  jenis         text not null default 'indoor' check (jenis in ('indoor', 'outdoor')),
  tarif_normal  numeric(14,2) not null check (tarif_normal >= 0),  -- tarif per jam di luar prime time
  tarif_prime   numeric(14,2) not null check (tarif_prime  >= 0),  -- tarif per jam saat prime time
  aktif         boolean not null default true
);

-- 2. PELANGGAN: orang yang menyewa lapangan / membeli paket member
create table pelanggan (
  id              bigint generated by default as identity primary key,
  nama            text not null,
  no_hp           text,
  email           text,
  tanggal_daftar  date not null default current_date
);

-- 3. PAKET_MEMBER: jenis paket jam main yang dijual (dibayar di muka)
create table paket_member (
  id                 bigint generated by default as identity primary key,
  nama_paket         text not null unique,
  jumlah_jam         int  not null check (jumlah_jam > 0),
  harga              numeric(14,2) not null check (harga >= 0),
  masa_berlaku_hari  int  not null default 30 check (masa_berlaku_hari > 0),
  aktif              boolean not null default true
);

-- 4. AKUN: bagan akun (Chart of Accounts)
--    saldo_normal 'D' = bertambah di Debit, 'K' = bertambah di Kredit
create table akun (
  kode          text primary key,
  nama          text not null,
  kategori      text not null check (kategori in ('Aset', 'Kewajiban', 'Ekuitas', 'Pendapatan', 'Beban')),
  saldo_normal  char(1) not null check (saldo_normal in ('D', 'K'))
);

-- 5. PERALATAN: raket & bola yang bisa disewa
create table peralatan (
  id           bigint generated by default as identity primary key,
  nama         text not null unique,
  jenis        text not null check (jenis in ('raket', 'bola')),
  tarif_sewa   numeric(14,2) not null check (tarif_sewa  >= 0),        -- per unit per booking
  denda_rusak  numeric(14,2) not null default 0 check (denda_rusak >= 0), -- denda per unit rusak
  stok         int not null default 0 check (stok >= 0)                -- stok tidak boleh minus
);


-- =====================================================================
--  B. TABEL TRANSAKSI
-- =====================================================================

-- 6. PEMBELIAN_PAKET: pelanggan membeli paket member
--    harga, jam_total, dan tanggal_kadaluarsa DIISI OTOMATIS oleh trigger
create table pembelian_paket (
  id                  bigint generated by default as identity primary key,
  pelanggan_id        bigint not null references pelanggan(id),
  paket_id            bigint not null references paket_member(id),
  tanggal_beli        date not null default current_date,
  tanggal_kadaluarsa  date,
  harga               numeric(14,2),
  jam_total           int,
  jam_terpakai        int not null default 0 check (jam_terpakai >= 0),
  metode_bayar        text not null default 'tunai' check (metode_bayar in ('tunai', 'transfer', 'qris')),
  check (jam_terpakai <= jam_total)
);

-- 7. BOOKING: pemesanan lapangan
--    kode_booking, durasi_jam, jenis_tarif, total_harga, status awal
--    DIISI OTOMATIS oleh trigger (lihat triggers.sql)
--    Alur status: menunggu -> dp -> lunas -> selesai
--                 (bisa 'batal' selama belum selesai)
create table booking (
  id                  bigint generated by default as identity primary key,
  kode_booking        text unique,
  pelanggan_id        bigint not null references pelanggan(id),
  lapangan_id         bigint not null references lapangan(id),
  tanggal             date not null,
  jam_mulai           time not null,
  jam_selesai         time not null,
  durasi_jam          int,
  jenis_tarif         text check (jenis_tarif in ('normal', 'prime', 'campuran', 'member')),
  total_harga         numeric(14,2) not null default 0,
  pembelian_paket_id  bigint references pembelian_paket(id), -- terisi jika main pakai paket member
  status              text not null default 'menunggu'
                      check (status in ('menunggu', 'dp', 'lunas', 'selesai', 'batal')),
  catatan             text,
  created_at          timestamptz not null default now(),
  check (jam_selesai > jam_mulai)
);

-- 8. PEMBAYARAN: uang yang diterima untuk sebuah booking (DP / pelunasan)
--    kolom "jenis" DIISI OTOMATIS: 'pelunasan' kalau jumlah = sisa tagihan
create table pembayaran (
  id            bigint generated by default as identity primary key,
  booking_id    bigint not null references booking(id),
  tanggal       date not null default current_date,
  jenis         text check (jenis in ('dp', 'pelunasan')),
  jumlah        numeric(14,2) not null check (jumlah > 0),
  metode_bayar  text not null default 'tunai' check (metode_bayar in ('tunai', 'transfer', 'qris')),
  created_at    timestamptz not null default now()
);

-- 9. SEWA_PERALATAN: peralatan yang disewa dalam sebuah booking
--    tarif & subtotal DIISI OTOMATIS dari tabel peralatan
create table sewa_peralatan (
  id               bigint generated by default as identity primary key,
  booking_id       bigint not null references booking(id),
  peralatan_id     bigint not null references peralatan(id),
  jumlah           int not null check (jumlah > 0),
  tarif            numeric(14,2),
  subtotal         numeric(14,2),
  tanggal_sewa     date not null default current_date,
  status_kembali   text not null default 'dipinjam'
                   check (status_kembali in ('dipinjam', 'dikembalikan', 'rusak')),
  jumlah_rusak     int not null default 0 check (jumlah_rusak >= 0),
  denda            numeric(14,2) not null default 0 check (denda >= 0),
  tanggal_kembali  date,
  check (jumlah_rusak <= jumlah)
);


-- =====================================================================
--  C. TABEL AKUNTANSI (diisi HANYA oleh trigger, bukan dari aplikasi)
-- =====================================================================

-- 10. JURNAL: header jurnal umum (satu transaksi = satu jurnal)
create table jurnal (
  id          bigint generated by default as identity primary key,
  no_bukti    text unique,              -- contoh: JU-00001 (otomatis)
  tanggal     date not null,
  keterangan  text not null,
  sumber      text not null,            -- asal transaksi: pembayaran / booking / pembelian_paket / sewa_peralatan
  sumber_id   bigint,                   -- id baris di tabel sumber
  created_at  timestamptz not null default now()
);

-- 11. JURNAL_DETAIL: baris debit & kredit (double-entry)
--     Setiap baris hanya boleh berisi debit ATAU kredit, tidak keduanya.
create table jurnal_detail (
  id         bigint generated by default as identity primary key,
  jurnal_id  bigint not null references jurnal(id) on delete cascade,
  akun_kode  text not null references akun(kode),
  debit      numeric(14,2) not null default 0 check (debit  >= 0),
  kredit     numeric(14,2) not null default 0 check (kredit >= 0),
  check ((debit > 0 and kredit = 0) or (kredit > 0 and debit = 0))
);


-- ---------------------------------------------------------------------
-- INDEX: mempercepat pencarian yang sering dipakai
-- ---------------------------------------------------------------------
create index idx_booking_jadwal       on booking (lapangan_id, tanggal);
create index idx_booking_status       on booking (status);
create index idx_pembayaran_booking   on pembayaran (booking_id);
create index idx_sewa_booking         on sewa_peralatan (booking_id);
create index idx_jurnal_tanggal       on jurnal (tanggal);
create index idx_jurnal_detail_jurnal on jurnal_detail (jurnal_id);
create index idx_jurnal_detail_akun   on jurnal_detail (akun_kode);


-- =====================================================================
--  D. VIEW: "tabel virtual" gabungan supaya query di frontend lebih mudah
--  security_invoker = true -> view tetap mengikuti aturan keamanan (RLS)
-- =====================================================================

-- Booking lengkap + nama pelanggan, nama lapangan, total dibayar & sisa
create view v_booking_lengkap with (security_invoker = true) as
select
  b.*,
  p.nama  as nama_pelanggan,
  p.no_hp as no_hp,
  l.nama  as nama_lapangan,
  coalesce(bayar.total, 0) as total_dibayar,
  case when b.pembelian_paket_id is not null or b.status = 'batal' then 0
       else b.total_harga - coalesce(bayar.total, 0)
  end as sisa_tagihan
from booking b
join pelanggan p on p.id = b.pelanggan_id
join lapangan  l on l.id = b.lapangan_id
left join (select booking_id, sum(jumlah) as total from pembayaran group by booking_id) bayar
       on bayar.booking_id = b.id;

-- Pembayaran + kode booking + nama pelanggan
create view v_pembayaran_lengkap with (security_invoker = true) as
select pb.*, b.kode_booking, p.nama as nama_pelanggan
from pembayaran pb
join booking   b on b.id = pb.booking_id
join pelanggan p on p.id = b.pelanggan_id;

-- Pembelian paket + nama pelanggan, nama paket, sisa jam
create view v_pembelian_paket_lengkap with (security_invoker = true) as
select pp.*,
       p.nama        as nama_pelanggan,
       pm.nama_paket as nama_paket,
       pp.jam_total - pp.jam_terpakai        as sisa_jam,
       (pp.tanggal_kadaluarsa < current_date) as kadaluarsa
from pembelian_paket pp
join pelanggan    p  on p.id  = pp.pelanggan_id
join paket_member pm on pm.id = pp.paket_id;

-- Sewa peralatan + nama peralatan, kode booking, nama pelanggan
create view v_sewa_lengkap with (security_invoker = true) as
select s.*,
       per.nama  as nama_peralatan,
       per.jenis as jenis_peralatan,
       b.kode_booking,
       p.nama    as nama_pelanggan
from sewa_peralatan s
join peralatan per on per.id = s.peralatan_id
join booking   b   on b.id   = s.booking_id
join pelanggan p   on p.id   = b.pelanggan_id;

-- Jurnal lengkap: header + detail + nama akun (dipakai Jurnal Umum, Buku Besar, Laporan)
create view v_jurnal_lengkap with (security_invoker = true) as
select jd.id,
       j.id        as jurnal_id,
       j.tanggal,
       j.no_bukti,
       j.keterangan,
       j.sumber,
       jd.akun_kode,
       a.nama      as nama_akun,
       a.kategori,
       a.saldo_normal,
       jd.debit,
       jd.kredit
from jurnal_detail jd
join jurnal j on j.id   = jd.jurnal_id
join akun   a on a.kode = jd.akun_kode;


-- =====================================================================
--  E. KEAMANAN: Row Level Security (RLS)
--  Aplikasi hanya memakai ANON KEY, jadi kita atur apa saja yang boleh
--  dilakukan oleh role "anon" (pengunjung tanpa login).
--  - Tabel jurnal & jurnal_detail HANYA boleh DIBACA. Isinya dibuat
--    oleh trigger, jadi jurnal tidak bisa dipalsukan dari aplikasi.
--  - Tidak ada izin DELETE: transaksi dibatalkan lewat status, bukan dihapus
--    (sesuai prinsip akuntansi: jejak audit harus tetap ada).
--  CATATAN: ini cukup untuk tugas kuliah. Untuk dipakai sungguhan,
--  tambahkan login (Supabase Auth) dan batasi policy ke role "authenticated".
-- =====================================================================

alter table lapangan        enable row level security;
alter table pelanggan       enable row level security;
alter table paket_member    enable row level security;
alter table akun            enable row level security;
alter table peralatan       enable row level security;
alter table pembelian_paket enable row level security;
alter table booking         enable row level security;
alter table pembayaran      enable row level security;
alter table sewa_peralatan  enable row level security;
alter table jurnal          enable row level security;
alter table jurnal_detail   enable row level security;

-- Hak akses dasar (GRANT) - harus sejalan dengan policy di bawahnya
grant usage on schema public to anon, authenticated;
grant select, insert, update on lapangan, pelanggan, paket_member, peralatan,
                                booking, sewa_peralatan              to anon, authenticated;
grant select, insert         on pembayaran, pembelian_paket         to anon, authenticated;
grant select                 on akun, jurnal, jurnal_detail         to anon, authenticated;
grant select on v_booking_lengkap, v_pembayaran_lengkap, v_pembelian_paket_lengkap,
                v_sewa_lengkap, v_jurnal_lengkap                    to anon, authenticated;

-- Master data: baca, tambah, ubah
create policy "baca lapangan"   on lapangan  for select to anon, authenticated using (true);
create policy "tambah lapangan" on lapangan  for insert to anon, authenticated with check (true);
create policy "ubah lapangan"   on lapangan  for update to anon, authenticated using (true) with check (true);

create policy "baca pelanggan"   on pelanggan for select to anon, authenticated using (true);
create policy "tambah pelanggan" on pelanggan for insert to anon, authenticated with check (true);
create policy "ubah pelanggan"   on pelanggan for update to anon, authenticated using (true) with check (true);

create policy "baca paket"   on paket_member for select to anon, authenticated using (true);
create policy "tambah paket" on paket_member for insert to anon, authenticated with check (true);
create policy "ubah paket"   on paket_member for update to anon, authenticated using (true) with check (true);

create policy "baca peralatan"   on peralatan for select to anon, authenticated using (true);
create policy "tambah peralatan" on peralatan for insert to anon, authenticated with check (true);
create policy "ubah peralatan"   on peralatan for update to anon, authenticated using (true) with check (true);

-- Akun: hanya baca
create policy "baca akun" on akun for select to anon, authenticated using (true);

-- Transaksi
create policy "baca booking"   on booking for select to anon, authenticated using (true);
create policy "tambah booking" on booking for insert to anon, authenticated with check (true);
create policy "ubah booking"   on booking for update to anon, authenticated using (true) with check (true);

create policy "baca pembayaran"   on pembayaran for select to anon, authenticated using (true);
create policy "tambah pembayaran" on pembayaran for insert to anon, authenticated with check (true);

create policy "baca pembelian paket"   on pembelian_paket for select to anon, authenticated using (true);
create policy "tambah pembelian paket" on pembelian_paket for insert to anon, authenticated with check (true);

create policy "baca sewa"   on sewa_peralatan for select to anon, authenticated using (true);
create policy "tambah sewa" on sewa_peralatan for insert to anon, authenticated with check (true);
create policy "ubah sewa"   on sewa_peralatan for update to anon, authenticated using (true) with check (true);

-- Jurnal: hanya baca
create policy "baca jurnal"        on jurnal        for select to anon, authenticated using (true);
create policy "baca jurnal detail" on jurnal_detail for select to anon, authenticated using (true);
